import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { requireAuth } from "@/lib/api-helpers";

/**
 * GET /api/generate/status?videoId=...
 *
 * Returns the current generation status of a video. The client can poll this
 * endpoint to show real-time progress while a video is being generated by the
 * background polling loop in generate.ts.
 */
export async function GET(req: NextRequest) {
  const { error, user } = await requireAuth();
  if (error) return error;

  const videoId = req.nextUrl.searchParams.get("videoId");
  if (!videoId) {
    return NextResponse.json(
      { error: "videoId query parameter is required" },
      { status: 400 }
    );
  }

  const video = await prisma.video.findFirst({
    where: { id: videoId, userId: user.id },
    select: {
      id: true,
      status: true,
      videoUrl: true,
      thumbnailUrl: true,
      model: true,
      title: true,
      duration: true,
      updatedAt: true,
    },
  });

  if (!video) {
    return NextResponse.json({ error: "Video not found" }, { status: 404 });
  }

  return NextResponse.json({ video });
}
